import chalk from "chalk";

export const LANGUAGES = {
  javascript: {
    dirs: [
      "node_modules",
      "dist",
      "build",
      ".next",
      "out",
      ".nuxt",
      ".output",
      ".cache",
      "coverage",
      ".turbo",
      ".svelte-kit",
      "storybook-static",
      ".angular",
      ".expo",
      ".yarn",
    ],
    color: chalk.yellow,
    icon: "🟨",
  },
  python: {
    dirs: [
      "__pycache__",
      "dist",
      "build",
      ".tox",
      ".pytest_cache",
      ".mypy_cache",
      ".coverage",
      "venv",
      ".venv",
      ".ipynb_checkpoints",
    ],
    color: chalk.cyan,
    icon: "🐍",
  },
  java: {
    dirs: [
      "target",
      "build",
      "out",
      ".gradle",
      "bin",
      ".settings",
      ".classpath",
      ".project",
      "*.class",
    ],
    color: chalk.red,
    icon: "☕",
  },
  rust: {
    dirs: [
      "target",
      "Cargo.lock",
      "debug",
      "release",
    ],
    color: chalk.magenta,
    icon: "🦀",
  },
  go: {
    dirs: [
      "bin",
      "pkg",
      "vendor",
      "dist",
    ],
    color: chalk.cyan,
    icon: "🐹",
  },
  common: {
    dirs: [
      ".DS_Store",
      "tmp",
      "temp",
      "logs",
      "*.log",
      ".history",
    ],
    color: chalk.gray,
    icon: "📁",
  },
};

export const GITIGNORE_IGNORE = [
  ".git",
  ".gitignore",
  ".github",
  ".vscode",
  ".idea",
  ".gitlab",
  ".circleci",
  ".travis.yml",
  ".gitmodules",
  ".gitattributes",
  ".editorconfig",
  ".eslintrc",
  ".prettierrc",
  ".stylelintrc",
  ".huskyrc",
  ".env",
  ".env.local",
  ".env.*.local",
  ".env.development",
  ".env.test",
  ".env.production",
  ".env.staging",
];
